var CATALOGO = [
  // ===== MINISTÉRIO DO INTERIOR =====
  {
    id: 'minint-sic',
    ministerio: 'Ministério do Interior',
    base: 'base-minint',
    orgao: 'Serviço de Investigação Criminal',
    sigla: 'SIC',
    vagas: 1186,
    tags: ['Investigação Criminal', 'Polícia Científica'],
    questoes: 376,
    descricao: 'Investigação criminal, perícias, polícia científica',
    icone: '\u{1F50D}',
    segundosPorQuestao: 60,
    bonus: ['Q_BONUS_minint_concurso', 'Q_BONUS_minint_sic'],
    cor: '#dc2626'
  },
  {
    id: 'minint-pn',
    ministerio: 'Ministério do Interior',
    base: 'base-minint',
    orgao: 'Polícia Nacional',
    sigla: 'PN',
    vagas: 3000,
    tags: ['Segurança Pública', 'Ordem Pública'],
    questoes: 376,
    descricao: 'Policiamento, segurança pública, ordem e tranquilidade',
    icone: '\u{1F6A8}',
    segundosPorQuestao: 60,
    bonus: ['Q_BONUS_minint_concurso'],
    cor: '#2563eb'
  },
  {
    id: 'minint-sme',
    ministerio: 'Ministério do Interior',
    base: 'base-minint',
    orgao: 'Serviço de Migração e Estrangeiros',
    sigla: 'SME',
    vagas: 1211,
    tags: ['Migração', 'Estrangeiros', 'Fronteiras'],
    questoes: 376,
    descricao: 'Controlo migratório, passaportes, vistos, fronteiras',
    icone: '\u{1F30D}',
    segundosPorQuestao: 60,
    bonus: ['Q_BONUS_minint_concurso'],
    cor: '#059669'
  },
  {
    id: 'minint-sp',
    ministerio: 'Ministério do Interior',
    base: 'base-minint',
    orgao: 'Serviço Penitenciário',
    sigla: 'SP',
    vagas: 1211,
    tags: ['Sistema Prisional', 'Reinserção Social'],
    questoes: 375,
    descricao: 'Administração prisional, reinserção social, custódia',
    icone: '\u{1F6E1}',
    segundosPorQuestao: 60,
    bonus: ['Q_BONUS_minint_concurso'],
    cor: '#7c3aed'
  },
  {
    id: 'minint-spcb',
    ministerio: 'Ministério do Interior',
    base: 'base-minint',
    orgao: 'Serviço de Protecção Civil e Bombeiros',
    sigla: 'SPCB',
    vagas: 1211,
    tags: ['Protecção Civil', 'Bombeiros', 'Emergência'],
    questoes: 375,
    descricao: 'Protecção civil, combate a incêndios, emergência',
    icone: '\u{1F692}',
    segundosPorQuestao: 60,
    bonus: ['Q_BONUS_minint_concurso'],
    cor: '#ea580c'
  },
  {
    id: 'psicotecnico',
    ministerio: 'Ministério do Interior',
    base: 'psicotecnico',
    orgao: 'Raciocínio Lógico e Psicotécnico',
    sigla: 'PSICO',
    vagas: 0,
    tags: ['Sequências', 'Analogias', 'Atenção', 'Lógica', 'Memória'],
    questoes: 87,
    descricao: 'Treino psicotécnico com temporizador de 30s por pergunta',
    icone: '\u{1F9E0}',
    segundosPorQuestao: 30,
    cor: '#8b5cf6'
  },
  {
    id: 'aptidao-fisica',
    ministerio: 'Ministério do Interior',
    base: 'aptidao-fisica',
    orgao: 'Aptidão Física e Preparação Psicológica',
    sigla: 'APTIDÃO',
    vagas: 0,
    tags: ['Aptidão Física', 'Psicologia', 'Saúde', '55%'],
    questoes: 30,
    descricao: 'Peso de 55% na avaliação · Preparação física, psicológica e exames médicos',
    icone: '\u{1F4AA}',
    segundosPorQuestao: 60,
    cor: '#dc2626'
  },
  // ===== MINISTÉRIO DA SAÚDE =====
  {
    id: 'saude-enfermagem',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'Serviço Nacional de Saúde — Enfermagem',
    sigla: 'SNS',
    vagas: 1828,
    tags: ['Cuidados de Enfermagem', 'Técnico de Enfermagem'],
    questoes: 299,
    descricao: 'Cuidados de enfermagem geral e especializada',
    icone: '\u{1FA7A}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-medicina',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'Serviço Nacional de Saúde — Medicina',
    sigla: 'SNS',
    vagas: 1545,
    tags: ['Médicos', 'Clínica Geral'],
    questoes: 317,
    descricao: 'Medicina geral, clínica médica, especialidades',
    icone: '\u{2695}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'Técnicos de Diagnóstico e Terapêutica (TDT)',
    sigla: 'SNS',
    vagas: 1255,
    tags: ['TDT'],
    questoes: 245,
    descricao: 'Análises clínicas, radiologia, farmácia, fisioterapia, etc.',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-analises-clinicas',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Análises Clínicas',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 260,
    descricao: 'Análises clínicas e laboratoriais',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-radiologia',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Radiologia',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 244,
    descricao: 'Radiologia e imagiologia',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-anatomia-patologica',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Anatomia Patológica',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 239,
    descricao: 'Anatomia patológica e citologia',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-cardiopneumologia',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Cardiopneumologia',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 240,
    descricao: 'Cardiopneumologia e fisiologia clínica',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-medicina-nuclear',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Medicina Nuclear',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 238,
    descricao: 'Medicina nuclear e radioisótopos',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-farmacia',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Farmácia',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 242,
    descricao: 'Farmácia hospitalar e comunitária',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-fisioterapia',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Fisioterapia',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 240,
    descricao: 'Fisioterapia e reabilitação',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-psicologia',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Psicologia',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 240,
    descricao: 'Psicologia clínica e da saúde',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-nutricao',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Nutrição',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 238,
    descricao: 'Nutrição e dietética',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-estomatologia',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Estomatologia',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 239,
    descricao: 'Estomatologia e saúde oral',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-tdt-eletromedicina',
    parentId: 'saude-tdt',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'TDT — Eletromedicina',
    sigla: 'SNS',
    vagas: 0,
    tags: ['TDT'],
    disciplina: true,
    questoes: 239,
    descricao: 'Eletromedicina e equipamentos hospitalares',
    icone: '\u{1F52C}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-regime-geral',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'Regime Geral — Administração da Saúde',
    sigla: 'SNS',
    vagas: 220,
    tags: ['Administrativo', 'Gestão'],
    questoes: 287,
    descricao: 'Administração pública, gestão, finanças, recursos humanos',
    icone: '\u{1F4C4}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-apoio-hospitalar',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'Apoio Hospitalar',
    sigla: 'SNS',
    vagas: 1067,
    tags: ['Apoio', 'Serviços Gerais'],
    questoes: 283,
    descricao: 'Higiene, maqueiro, secretariado clínico, vigilância, transporte',
    icone: '\u{1F3E5}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  {
    id: 'saude-assistentes-sociais',
    ministerio: 'Ministério da Saúde',
    base: 'base-saude',
    orgao: 'Assistentes Sociais',
    sigla: 'SNS',
    vagas: 85,
    tags: ['Serviço Social', 'Acção Social'],
    questoes: 279,
    descricao: 'Serviço social na saúde, protecção social, inclusão',
    icone: '\u{1F91D}',
    segundosPorQuestao: 60,
    cor: '#0891b2'
  },
  // ===== MINISTÉRIO DA EDUCAÇÃO =====
  {
    id: 'educacao-professores',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Professores do Ensino Primário e Secundário',
    sigla: 'MED',
    vagas: 8000,
    tags: ['Docente', 'Professor'],
    questoes: 284,
    descricao: 'Professores — língua portuguesa, pedagogia, ética',
    icone: '\u{1F393}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-regime-geral',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Regime Geral — Administração da Educação',
    sigla: 'MED',
    vagas: 1000,
    tags: ['Administrativo', 'Secretaria', 'Gestão'],
    questoes: 287,
    descricao: 'Administração, secretaria escolar, arquivo, gestão',
    icone: '\u{1F4DD}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-matematica',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Matemática',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Matemática — ensino secundário',
    icone: '\u{1F4D0}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-fisica',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Física',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Física — ensino secundário',
    icone: '\u{269B}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-quimica',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Química',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Química — ensino secundário',
    icone: '\u{2697}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-biologia',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Biologia',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Biologia — ensino secundário',
    icone: '\u{1F331}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-historia',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — História',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'História — ensino secundário',
    icone: '\u{1F4DC}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-geografia',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Geografia',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Geografia — ensino secundário',
    icone: '\u{1F30E}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-portugues',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Língua Portuguesa',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 281,
    descricao: 'Língua Portuguesa — ensino secundário',
    icone: '\u{1F4D6}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-ingles',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Inglês',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Inglês — ensino secundário',
    icone: '\u{1F4DA}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-informatica',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Informática',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 110,
    descricao: 'Informática — ensino secundário',
    icone: '\u{1F4BB}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-filosofia',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Filosofia',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Filosofia — ensino secundário',
    icone: '\u{1F4AD}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  {
    id: 'educacao-disciplina-educacao-fisica',
    parentId: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplina — Educação Física',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 278,
    descricao: 'Educação Física — ensino secundário',
    icone: '\u{1F3C3}',
    segundosPorQuestao: 60,
    cor: '#ca8a04'
  },
  // Container card for education disciplines
  {
    id: 'educacao-disciplinas',
    ministerio: 'Ministério da Educação',
    base: 'base-educacao',
    orgao: 'Disciplinas de Especialidade',
    sigla: 'MED',
    vagas: 0,
    tags: ['Professor', 'Especialidade'],
    questoes: 0,
    descricao: 'Matemática, Física, Química, Biologia, História, Geografia, Português, Inglês, Informática, Filosofia',
    icone: '\u{1F4DA}',
    container: true,
    cor: '#ca8a04'
  }
];
